{% set name = "djlint" %}
{% set version = "1.31.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/djlint-{{ version }}.tar.gz
  sha256: a11739e2f919f760b3986eb13d06e00171f3bd342b8d88e9bd914a4260eaa8ce

build:
  entry_points:
    - djlint = djlint:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7,<4.0
    - poetry-core >=1.0.0
    - pip
  run:
    - python >=3.7,<4.0
    - click >=8.0.1,<9.0.0
    - pyyaml >=6.0.0,<7.0.0
    - colorama >=0.4.4,<0.5.0
    - regex >=2022.1.18,<2023.0.0
    - tqdm >=4.62.2,<5.0.0
    - tomli >=2.0.1,<3.0.0
    - pathspec >=0.9.0,<0.10.0
    - importlib-metadata >=4.11.0,<5.0.0
    - html-void-elements >=0.1.0,<0.2.0
    - html-tag-names >=0.1.2,<0.2.0
    - jsbeautifier >=1.14.4,<2.0.0
    - cssbeautifier >=1.14.4,<2.0.0
    - json5 >=0.9.5,<0.10.0

test:
  imports:
    - djlint
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Riverside-Healthcare/djlint
  summary: HTML Template Linter and Formatter
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
