{% set name = "djlint" %}
{% set version = "1.40.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/djlint-{{ version }}.tar.gz
  sha256: 76949030ddfe7334bcde9bcb022133c5d7bb7d292ea7717fc8df425bad4b41c3

build:
  entry_points:
    - djlint = djlint:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - typing_extensions >=3.7.4
    - click >=8.2.0
    - colorama >=0.4.4
    - cssbeautifier >=1.13.0
    - html-tag-names >=0.1.2
    - html-void-elements >=0.1
    - jsbeautifier >=1.13.0
    - json5 >=0.10.0
    - pathspec >=0.9.0
    - pyyaml >=5.1
    - regex >=2021.8.21
    - tomli >=2.0.1
    - tqdm >=4.62.2

test:
  imports:
    - djlint
  commands:
    - pip check
    - djlint --help
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/djlint/djLint
  summary: HTML Template Linter and Formatter
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
