{% set name = "djlint" %}
{% set version = "1.36.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/djlint-{{ version }}.tar.gz
  sha256: 17254f218b46fe5a714b224c85074c099bcb74e3b2e1f15c2ddc2cf415a408a1

build:
  entry_points:
    - djlint = djlint:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - typing_extensions >=3.6.6
    - click >=8.0.1
    - colorama >=0.4.4
    - cssbeautifier >=1.14.4
    - html-tag-names >=0.1.2
    - html-void-elements >=0.1
    - jsbeautifier >=1.14.4
    - json5 >=0.9.11
    - pathspec >=0.12
    - pyyaml >=6
    - regex >=2023
    - tomli >=2.0.1
    - tqdm >=4.62.2

test:
  imports:
    - djlint
  commands:
    - pip check
    - djlint --help
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/djlint/djLint
  summary: HTML Template Linter and Formatter
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
